#!/usr/bin/env php
<?php
$helptext = "
Usage: makesite [sitename]

if not specified, interactive mode will ask for sitename. This can be just the subdomain, or the full url minus http://

";

// get config
if(!file_exists(__DIR__."/config.json")){
  // copy(__DIR__."/config.json.example", __DIR__."/config.json");
  die('Configuration has not been completed. Copy "config.json.example" to "config.json" and fill in your settings.');
}
$config = json_decode(file_get_contents(__DIR__."/config.json"), true);
$allsitesroot = $config['allsitesroot'];
$configroot = $config['configroot'];
$publicdns = $config['publicdns'];

$basehostname = $publicdns ;

$username = get_current_user();

if(count($argv) > 2) die(colorize('Too many arguments!' . "\n", 'FAILURE'));

$stdin = fopen('php://stdin', 'r');

$servername = (count($argv) === 2) ? $argv[1] : false;

// See if asking for help...
if(in_array($servername, ['-h', '--help'])) die(colorize($helptext, "WARNING"));

if($servername == false) {

	echo colorize(PHP_EOL."Specify the hostname. This can be the full url (without http://), or just the subdomain, which will be prefixed to: $basehostname" . PHP_EOL, "NOTE");
	echo "> ";
	$servername = clean(fgets($stdin));
}

if(empty($servername)) {
	echo colorize(PHP_EOL."You must specify a hostname", "FAILURE");
	die('exiting' . PHP_EOL);
}

$servername =  clean($servername);

if(strpos($servername, '.') === false) $servername = "$servername.$basehostname";

if(is_dir("$allsitesroot/$servername") || file_exists("$configroot/$servername.conf")){
	echo colorize(PHP_EOL."This site already exists!!!".PHP_EOL, "FAILURE");
	die();
}


$aliases = [];
$alias_response = "XXX";
while(!empty($alias_response)){
  echo colorize("Your hostname will be:   $servername", 'NOTE');
  echo colorize("Enter an alias below, or press enter to continue.", 'NOTE');
  echo "> ";
  $alias_response = strtolower( trim(fgets($stdin)) );
  if(!empty($alias_response))
    $aliases[] = $alias_response;
}
$apache_aliases = [];
foreach($aliases as $a){
  $apache_aliases[] = "ServerAlias $a";
}
$apache_aliases = implode("\n", $apache_aliases). "\n";
echo colorize("The site: $servername, will be created. CONTINUE? [yes/no]", 'NOTE');
echo "> ";
$confirm = strtolower( trim(fgets($stdin)) );
if(!in_array($confirm, ['y', 'yes'])) die('exiting' . PHP_EOL);

fclose($stdin);

$configtemplate = '<VirtualHost *:80>

ServerName {{servername}}:80
'.$apache_aliases.'
DocumentRoot '.$allsitesroot.'/{{servername}}/public_html
ErrorLog /private/var/log/apache2/{{servername}}_error_log
CustomLog /private/var/log/apache2/{{servername}}_access_log combined
ServerAdmin webmaster@localhost
DirectoryIndex index.html index.php index.htm

<Directory "'.$allsitesroot.'/{{servername}}/public_html">
		Options -Indexes
		AllowOverride All
		allow from all
		Require all granted
</Directory>

</VirtualHost>

<VirtualHost *:443>

ServerName {{servername}}:443
'.$apache_aliases.'
DocumentRoot '.$allsitesroot.'/{{servername}}/public_html
ErrorLog /private/var/log/apache2/{{servername}}_error_log
CustomLog /private/var/log/apache2/{{servername}}_access_log combined
ServerAdmin webmaster@localhost
DirectoryIndex index.html index.php index.htm

<Directory "'.$allsitesroot.'/{{servername}}/public_html">
		Options -Indexes
		AllowOverride All
		allow from all
		Require all granted
</Directory>

SSLCertificateFile "/usr/local/etc/httpd/server.crt"
SSLCertificateKeyFile "/usr/local/etc/httpd/server.key"

</VirtualHost>
';

if(!is_dir("$allsitesroot/$servername")) mkdir("$allsitesroot/$servername");
if(!is_dir("$allsitesroot/$servername/public_html")) mkdir("$allsitesroot/$servername/public_html");
$startercontent = '<body style="background-color:black;color:white;font-family:monospace;text-align:center; margin:0;padding:0">
	<svg style="height: 100vh;width: 100vw;text-align: center;">
		<text style="fill: white;font-size: 50vh;width: 100%;" dominant-baseline="middle" y="25%">Hello</text>
		<text style="fill: white;font-size: 20vh;width: 100%;" dominant-baseline="middle" y="50%">'.$servername.'</text>
	</svg>
</body>';
if(!file_exists("$allsitesroot/$servername/public_html/index.html"))
	file_put_contents("$allsitesroot/$servername/public_html/index.html", $startercontent);


$hostcontents = str_replace('{{servername}}', $servername, $configtemplate);
exec("sudo touch $configroot/$servername.conf && sudo chown $username $configroot/$servername.conf");
file_put_contents("$configroot/$servername.conf", $hostcontents);
exec("ln -s $configroot/$servername.conf $allsitesroot/$servername/site.conf");

exec("echo \"127.0.0.1     $servername\" | sudo tee -a /etc/hosts > /dev/null");


exec('sudo apachectl restart');

exec("permit _www '$allsitesroot/$servername/public_html' w");

echo colorize("\n\nDone! \n$servername is now available.\n\nRun `sudo service httpd restart` if changes haven't taken effect\n\n
Go to the site directory: `cd $allsitesroot/$servername`\n\n", "SUCCESS");


exec("open http://$servername");


	// copy to /etc/httpd/conf.d/*.conf


function colorize($text, $status) {
 $out = "";
 switch($status) {
  case "SUCCESS":
   $out = "[32m"; //Green
   break;
  case "FAILURE":
   $out = "[31m"; //Red
   break;
  case "WARNING":
   $out = "[33m"; //Yellow
   break;
  case "NOTE":
   $out = "[36m"; //Blue
   break;
  default:
   throw new Exception("Invalid status: " . $status);
 }
 return chr(27) . "$out" . "$text" . chr(27) . "[0m" . PHP_EOL;
}

function clean($input){
	return trim(preg_replace('/[^a-z0-9\-\.]/', '', strtolower(trim($input))), '-');
}
