#!/bin/sh

GROUP=$1
DIRECTORY=$2
PERMS=$3

ALLPERMS='list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit'

if [ -z "$PERMS" ] || [ "$PERMS" = "r" ];
then
        PERMS='list,search,readattr,readextattr,readsecurity,file_inherit,directory_inherit'
        
fi

if [ "$PERMS" = "w" ];
then
        PERMS="$ALLPERMS"
fi

if [ -z "$DIRECTORY" ] || [ -z "$GROUP" ]; 
then 
        echo "format: 'permit <group> <directory> <perms=r|(w)>' You must specify the directory to make permissible by specified group"; 
        exit;

else
        echo "working..."
        # remove existing ACLs first

        sudo chmod -R -ai "$GROUP allow $ALLPERMS" "$DIRECTORY"
		sudo chmod -R +ai "$GROUP allow $PERMS" "$DIRECTORY"
		ls -lea "$DIRECTORY/.."
fi
